---
title: "Simple Data Manipulation & Visualization - Tidy data"
author: "Vangelis Theodorakis, Xueqi Cao"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  fig.width=12, fig.height=12, 
  echo=T, warning=FALSE, message=FALSE, 
  results="show"
)


# setwd("./lectures")
```
## Setup

```{r, config, echo = TRUE}
library(data.table)
library(magrittr)
library(tidyr)
```


## Question 1

Read the weather dataset `weather.txt`. It contains the minimal and maximal temperature on a certain city (id) over different dates (year, month, d1-d31). Why is this dataset messy? How would a tidy version of it look like? Create its tidy version.

```{r, echo = T, results = "show"}
messy_dt <- fread("extdata/weather.txt")
messy_dt %>% head
dim(messy_dt)
```

```{r}
## Why is it messy?
## 1. Variables are stored as columns (days)
## 2. A single entity is scattered across many cells (date)
## 3. Element column is not a variable.
##
## Tidy version: id, date, tmin, tmax
```


```{r}
tidy_dt <- messy_dt %>% 
  melt(id.vars=c('id', 'year', "month", "element"), na.rm=TRUE) %>%
  .[, variable := gsub('d', '', variable)] %>% 
  unite(col=date, year, month, variable, sep='-') %>% 
  dcast(... ~ element) %>% 
  .[, date := as.Date(date)]





## wide -> long
dt <- melt(messy_dt, id.vars = c("id", "year", "month", "element"), variable.name = "day") 
# you can ignore the warning message
dt[, day := as.integer(gsub("d", "", day))]

# Join all date related columns into one. Use unite or paste
# 1. Using unite():
dt <- unite(dt, "date", c("year", "month", "day"), sep = "-", remove = TRUE)

# 2. Using paste():
# dt[, date := paste(year, month, day, sep = "-")] # convert to date
# dt[, c("year", "month", "day") := NULL] # remove reduntant columns


dt <- dcast(dt, ... ~ element, value.var = "value") # long -> wide

dt <- dt[!(is.na(TMAX) & is.na(TMIN))] # remove entries with both NA values,
                                       # na.omit(dt) would also do the job

head(dt)

dim(dt)
```

```{r}
# An alternative tidy code version
tidy_dt <- messy_dt %>% 
  melt(id.vars=c('id', 'year', 'month', 'element'), na.rm=TRUE) %>% 
  .[, variable := gsub('d', '', variable)] %>% 
  unite(date, year, month, variable, sep='-') %>% 
  dcast(... ~ element) %>% 
  .[, date := as.Date(date)]
```
